// SimEvents -> one-shot cues, plus looping BGM bed, lore ambience and story VO.
//
// Directive history:
//   2026-08-04 — "SFX + BGM only, NO voice narration."
//   2026-08-09 — AMENDED by the operator: 연출용 영상·음성·사운드 추가.
//     Voice is now allowed, but only as STORY NARRATION on beats the game
//     already shows as text (StoryCatalog lines rendered by SpeechBubbleView),
//     generated by tools/audio/gen_voice.py. The 2026-08-04 rule still holds
//     INSIDE sound effects: cue-* prompts continue to forbid vocals, because a
//     voice baked into a combat one-shot cannot be muted independently or
//     translated. VO is a separate source with its own volume path.
//
// Voice pool + pitch jitter (improvement-brainstorm.md TOP 1): a single
// AudioSource replayed every cue overlaps identical waveforms in phase, so a
// combo's rapid `hit` retriggers read as one buzzing tone. A small round-robin
// pool spreads concurrent one-shots across voices and a deterministic pitch
// jitter (±6%) de-phases repeats so a burst sounds like many strikes, not one.
// WebGL contract: AudioSource.pitch is supported but MUST stay positive
// (docs.unity3d.com/Manual/webgl-audio.html); the jitter range [0.94,1.06]
// never crosses zero. `priority` is a no-op on WebGL, so voice spreading is the
// only way to keep a loud cue from stealing a quiet one.
using System.Collections.Generic;
using CinderCourt.Sim;
using UnityEngine;

namespace CinderCourt.View
{
    public sealed class AudioDirector : MonoBehaviour
    {
        const string MuteKey = "abyssal-lantern:cinder-court:muted";
        // Enough voices for the loudest realistic frame (nova hit + finisher +
        // kill + pickup) without letting round-robin wrap onto a still-ringing
        // voice mid-burst. WebGL has no hardware voice cap, so this is only
        // about phase spreading, not a channel budget.
        const int VoiceCount = 6;
        // ±6% keeps every retrigger recognizably the same cue while breaking the
        // in-phase overlap that makes repeats buzz. Stays > 0 for WebGL.
        const float PitchJitter = 0.06f;

        readonly AudioSource[] _voices = new AudioSource[VoiceCount];
        int _voiceCursor;
        // View-only presentation RNG. NOT the sim — pitch never feeds a tick, so
        // seeding it deterministically keeps EditMode assertions reproducible
        // without touching the frozen deterministic-sim contract.
        uint _pitchRng = 0x9E3779B9u;

        AudioSource _bgm;
        AudioClip _strike, _hit, _kill, _nova, _ward, _pickup, _wave, _gameover, _lore;
        AudioClip _bgmLegacy;
        AudioClip _click, _footstep;
        // Graded loot cues + the toast whoosh. All three are optional: a build
        // without them falls back to cue-pickup (grades) or stays silent (toast),
        // which is the same null-safe contract PlayClick/PlayFootstep keep.
        AudioClip _lootFine, _lootEpic, _toast;
        // Dungeon-kit cues (2026-08-09). Each REPLACES a volume-variation of a
        // base clip that has stood as an "interim contract" since the kit
        // shipped — see OnEvents. Every one is optional and falls back to the
        // exact interim mapping it supersedes, so a partial generation run
        // degrades cue by cue instead of going silent.
        AudioClip _dash, _bolt, _pulse, _levelUp, _eliteDown,
                  _extraction, _bossPhase2, _comboFinisher, _bossSpawned;
        readonly Dictionary<string, AudioClip> _bgmByContext =
            new Dictionary<string, AudioClip>(4);
        bool _muted;

        // --- story VO (2026-08-09 amendment) ------------------------------
        // A DEDICATED source, not the 6-voice one-shot pool: narration must not
        // be pitch-jittered (it would warble a human voice), must not be
        // round-robined away mid-line by a burst of combat cues, and has to be
        // stoppable as a unit when the run ends.
        AudioSource _vo;
        readonly Dictionary<string, AudioClip> _voByKey =
            new Dictionary<string, AudioClip>(8);
        // Ducking. The bed drops to this fraction while a line plays and eases
        // back afterwards, so narration sits above the music without the music
        // disappearing. Ramps run on UNSCALED time: story beats routinely fire
        // while the game is paused for a guidance card, and CLAUDE.md §4g is
        // explicit that a scaled timer never advances at timeScale 0 — a duck
        // that never recovers would leave the lobby quiet forever.
        const float VoDuck = 0.4f;
        const float VoDuckFade = 0.3f;
        float _bgmBaseVolume = 0.35f;
        float _duck = 1f;          // current multiplier, 1 = no duck

        public bool Muted => _muted;

        void Awake()
        {
            for (var i = 0; i < VoiceCount; i++)
            {
                var voice = gameObject.AddComponent<AudioSource>();
                voice.playOnAwake = false;
                _voices[i] = voice;
            }

            _strike = Resources.Load<AudioClip>("Audio/cue-strike");
            _hit = Resources.Load<AudioClip>("Audio/cue-hit");
            _kill = Resources.Load<AudioClip>("Audio/cue-kill");
            _nova = Resources.Load<AudioClip>("Audio/cue-nova");
            _ward = Resources.Load<AudioClip>("Audio/cue-ward");
            _pickup = Resources.Load<AudioClip>("Audio/cue-pickup");
            _wave = Resources.Load<AudioClip>("Audio/cue-wave");
            _gameover = Resources.Load<AudioClip>("Audio/cue-gameover");
            _lore = Resources.Load<AudioClip>("Audio/cue-lore");
            _click = Resources.Load<AudioClip>("Audio/cue-click");
            _footstep = Resources.Load<AudioClip>("Audio/cue-footstep");
            _lootFine = Resources.Load<AudioClip>("Audio/cue-loot-fine");
            _lootEpic = Resources.Load<AudioClip>("Audio/cue-loot-epic");
            _toast = Resources.Load<AudioClip>("Audio/cue-toast");
            _dash = Resources.Load<AudioClip>("Audio/cue-dash");
            _bolt = Resources.Load<AudioClip>("Audio/cue-bolt");
            _pulse = Resources.Load<AudioClip>("Audio/cue-pulse");
            _levelUp = Resources.Load<AudioClip>("Audio/cue-levelup");
            _eliteDown = Resources.Load<AudioClip>("Audio/cue-elite-down");
            _extraction = Resources.Load<AudioClip>("Audio/cue-extraction");
            _bossPhase2 = Resources.Load<AudioClip>("Audio/cue-boss-phase2");
            _comboFinisher = Resources.Load<AudioClip>("Audio/cue-combo-finisher");
            _bossSpawned = Resources.Load<AudioClip>("Audio/cue-boss-spawned");

            // W12 (seed §2, 2026-08-08): per-context BGM tracks generated via
            // the ElevenLabs Music API (Audio/bgm-{intro,lobby,loading,stage}).
            // The legacy cue-bgm bed stays as the universal fallback so a build
            // missing the new tracks keeps its music.
            _bgmLegacy = Resources.Load<AudioClip>("Audio/cue-bgm");
            var bgmClip = _bgmLegacy;
            if (bgmClip != null)
            {
                _bgm = gameObject.AddComponent<AudioSource>();
                _bgm.clip = bgmClip;
                _bgm.loop = true;
                _bgm.volume = _bgmBaseVolume;
                _bgm.playOnAwake = false;
            }

            // Story VO source. pitch stays 1: the one-shot pool deliberately
            // detunes ±6% per call to de-phase repeated cues, which is correct
            // for a strike and wrong for a narrator — it would make every line
            // sound like a different speaker. It also cannot share the pool at
            // all: pitch is a property of the SOURCE, so the 7th cue after a
            // line would wrap round-robin onto the still-playing narration and
            // re-pitch it mid-word (6 cues in a few seconds is routine combat).
            _vo = gameObject.AddComponent<AudioSource>();
            _vo.playOnAwake = false;
            _vo.loop = false;
            _vo.pitch = 1f;
            _vo.volume = 0.9f;

            _muted = PlayerPrefs.GetInt(MuteKey, 0) == 1;
            ApplyMute();
        }

        void ApplyMute()
        {
            if (_bgm != null)
            {
                if (_muted && _bgm.isPlaying) _bgm.Pause();
                else if (!_muted && !_bgm.isPlaying) _bgm.Play();
            }
            // Mute is a player-facing promise: a narrator that keeps talking
            // through it is the loudest possible way to break it.
            if (_muted) StopVoice();
        }

        /// <summary>
        /// Story narration for a beat key ("cinder-span-bossEntry", ...).
        /// Loads Audio/vo-{key} once and caches misses too, so a build that
        /// ships no VO pays one failed load per key and then stays silent —
        /// the same additive contract PlayClick/PlayToastCue keep. Silence is
        /// always an acceptable outcome here: the line is ALREADY on screen as
        /// text (SpeechBubbleView), so VO is reinforcement, never the only
        /// carrier of the beat.
        ///
        /// RETURNS the clip length in seconds (0 when nothing plays) so the
        /// caller can hold the matching bubble for at least that long. That
        /// return value is not a convenience — MEASURED, the generated lines
        /// run 2.30-5.04 s while SpeechBubbleView's hold formula
        /// (clamp(1.5 + 0.058*chars, 2.2, 5.2)) gives the same lines 2.49-3.59 s,
        /// because the formula is paced for READING (~17 chars/s) and the TTS
        /// speaks at ~7. Six of the first eight lines outlasted their own
        /// bubble by up to 1.74 s — a disembodied voice over an empty screen.
        /// </summary>
        public float PlayVoice(string beatKey)
        {
            if (_muted || _vo == null || string.IsNullOrEmpty(beatKey)) return 0f;
            if (!_voByKey.TryGetValue(beatKey, out var clip))
            {
                clip = Resources.Load<AudioClip>("Audio/vo-" + beatKey);
                _voByKey[beatKey] = clip;   // cache misses too
            }
            if (clip == null) return 0f;
            // A newer beat always wins: two lines over each other is worse than
            // a truncated one, and the visible bubble has already moved on.
            _vo.Stop();
            _vo.clip = clip;
            _vo.Play();
            return clip.length;
        }

        /// <summary>
        /// Stops narration and releases the duck. Must be called from every
        /// run-ending path — CLAUDE.md §4o: a surface that holds the run has to
        /// come down when the run does, or the lobby inherits a voice from a
        /// fight that is already over.
        /// </summary>
        public void StopVoice()
        {
            if (_vo != null && _vo.isPlaying) _vo.Stop();
        }

        /// <summary>True while a narration line is sounding (test seam).</summary>
        public bool VoicePlaying => _vo != null && _vo.isPlaying;

        /// <summary>
        /// Duck target for the bed: dipped while narration sounds, 1 otherwise.
        /// Pure function of the playing flag so EditMode can assert it without
        /// an audio device.
        /// </summary>
        internal static float DuckTarget(bool voicePlaying)
            => voicePlaying ? VoDuck : 1f;

        /// <summary>
        /// One step of the duck ramp. Separated from Update and fed an explicit
        /// dt so the curve is EditMode-testable — the same injected-dt shape the
        /// rest of the view lane uses for time-based behaviour.
        /// </summary>
        internal static float StepDuck(float current, float target, float dt)
        {
            if (VoDuckFade <= 0f) return target;
            var step = dt / VoDuckFade;
            return Mathf.MoveTowards(current, target, step);
        }

        void Update()
        {
            if (_bgm == null) return;
            // Time.unscaledDeltaTime, never deltaTime: story beats fire while a
            // guidance card holds timeScale at 0 (§4g), and a scaled ramp there
            // never advances — the bed would stay ducked into the next screen.
            _duck = StepDuck(_duck, DuckTarget(VoicePlaying), Time.unscaledDeltaTime);
            _bgm.volume = _bgmBaseVolume * _duck;
        }

        /// <summary>W12: UI button click. Null-safe — silent until the cue
        /// asset ships.</summary>
        public void PlayClick() => Play(_click, 0.8f);

        /// <summary>W12: movement footstep tick. The caller owns the cadence
        /// (view-side distance accumulator); this just voices it.</summary>
        public void PlayFootstep() => Play(_footstep, 0.45f);

        /// <summary>Graded acquisition cue for ONE collected pickup.
        ///
        /// Owned by the caller, not by <see cref="OnEvents"/>: SimEvents carries a
        /// bare PickupCollected flag with no grade and no count, so a frame that
        /// swept up three drops raised one flag. GameView diffs the published
        /// pickup list and calls this once per pickup with the grade that pickup
        /// actually carried, which is why PickupCollected/EquipDropped no longer
        /// voice themselves in OnEvents — that would double-play.
        ///
        /// Missing grade cues fall back to cue-pickup, so a build without the
        /// generated assets keeps the acquisition audible at Basic.</summary>
        public void PlayLootCue(LootGrade grade)
        {
            var clip = grade == LootGrade.Epic ? _lootEpic
                     : grade == LootGrade.Fine ? _lootFine
                     : null;
            Play(clip != null ? clip : _pickup);
        }

        /// <summary>The toast's own arrival whoosh. Deliberately quiet: it lands
        /// on the same frame as PlayLootCue and must sit under it, never mask it.
        /// Silent until the cue asset ships.</summary>
        public void PlayToastCue() => Play(_toast, 0.45f);

        /// <summary>W12: swap the looping BGM bed for a context ("intro",
        /// "lobby", "loading", "stage"). Loads Audio/bgm-{context} once and
        /// caches it; a missing track falls back to the legacy cue-bgm bed.
        /// Same-clip calls are no-ops so state transitions can call this
        /// unconditionally without restarting the loop.</summary>
        public void SetBgmContext(string context)
        {
            AudioClip clip = null;
            if (!string.IsNullOrEmpty(context))
            {
                if (!_bgmByContext.TryGetValue(context, out clip))
                {
                    clip = Resources.Load<AudioClip>("Audio/bgm-" + context);
                    _bgmByContext[context] = clip;   // cache misses too
                }
            }
            if (clip == null) clip = _bgmLegacy;
            if (clip == null) return;   // no music shipped at all

            if (_bgm == null)
            {
                // Legacy bed was absent in Awake but a context track exists.
                _bgm = gameObject.AddComponent<AudioSource>();
                _bgm.loop = true;
                // Base, not final: Update multiplies by the VO duck each frame.
                _bgm.volume = _bgmBaseVolume * _duck;
                _bgm.playOnAwake = false;
            }
            if (_bgm.clip == clip) { ApplyMute(); return; }
            var wasPlaying = _bgm.isPlaying;
            _bgm.Stop();
            _bgm.clip = clip;
            if (!_muted && (wasPlaying || !_bgm.isPlaying)) _bgm.Play();
        }

        public void ToggleMute()
        {
            _muted = !_muted;
            PlayerPrefs.SetInt(MuteKey, _muted ? 1 : 0);
            PlayerPrefs.Save();
            ApplyMute();
        }

        /// <summary>Deterministic view-only jitter in [1-PitchJitter, 1+PitchJitter],
        /// advancing an xorshift32 state. Pure given the state, so EditMode can
        /// assert its bounds and that consecutive draws differ. Never touches the
        /// sim RNG or any tick input.</summary>
        internal static float NextPitch(ref uint state)
        {
            // xorshift32 — full-period, cheap, no allocation.
            state ^= state << 13;
            state ^= state >> 17;
            state ^= state << 5;
            var unit = (state & 0xFFFFFFu) / (float)0x1000000; // [0,1)
            return 1f + (unit * 2f - 1f) * PitchJitter;
        }

        void Play(AudioClip clip, float volume = 1f)
        {
            if (_muted || clip == null || _voices[0] == null) return;
            var voice = _voices[_voiceCursor];
            _voiceCursor = (_voiceCursor + 1) % VoiceCount;   // round-robin
            voice.pitch = NextPitch(ref _pitchRng);
            voice.PlayOneShot(clip, volume);   // overlap allowed, no trimming
        }

        public void OnEvents(SimEvents events)
        {
            if ((events & SimEvents.PlayerStruck) != 0) Play(_strike);
            if ((events & SimEvents.EnemyHit) != 0) Play(_hit);
            if ((events & SimEvents.EnemyKilled) != 0) Play(_kill);
            if ((events & SimEvents.NovaCast) != 0) Play(_nova);
            if ((events & SimEvents.WardCast) != 0) Play(_ward);
            // PickupCollected is NOT voiced here: the flag carries no grade and
            // no count, so it cannot choose between cue-pickup/fine/epic. GameView
            // resolves both from the published pickup list and calls PlayLootCue
            // once per collected item.
            if ((events & SimEvents.WaveStarted) != 0)
            {
                Play(_wave);
                Play(_lore, 0.5f);   // ambient texture under the lore line
            }
            if ((events & SimEvents.GameOver) != 0) Play(_gameover);
            // Campaign events reuse existing cues (no extra generation needed):
            if ((events & SimEvents.HazardPulse) != 0) Play(_hit, 0.6f);
            if ((events & SimEvents.AltarBlessing) != 0) Play(_ward, 0.7f);
            // EquipDropped likewise routes through PlayLootCue (a shard pickup
            // raises PickupCollected AND EquipDropped in the same tick — voicing
            // both here played cue-pickup twice for one item).
            if ((events & SimEvents.StageCleared) != 0)
            {
                Play(_wave);          // triumphant horn
                Play(_pickup, 0.9f);  // sparkle on top
            }
            // Dungeon kit events (presentation spec #18). Each line prefers its
            // DEDICATED cue and falls back to the volume-variation of a base
            // clip that served as the interim contract before dedicated cues
            // existed. The fallback is not decoration: cue generation is
            // incremental, so a half-generated set must degrade cue by cue
            // rather than dropping the event.
            if ((events & SimEvents.DashUsed) != 0)
                PlayOrFallback(_dash, 1f, _strike, 0.5f);
            if ((events & SimEvents.BoltCast) != 0)
                PlayOrFallback(_bolt, 1f, _nova, 0.45f);
            if ((events & SimEvents.PulseCast) != 0)
                PlayOrFallback(_pulse, 1f, _ward, 0.6f);
            if ((events & SimEvents.LevelUp) != 0)
            {
                if (_levelUp != null) Play(_levelUp, 1f);
                else { Play(_pickup, 1f); Play(_wave, 0.4f); }   // fanfare layer
            }
            if ((events & SimEvents.EliteDown) != 0)
                PlayOrFallback(_eliteDown, 1f, _kill, 1f);
            if ((events & SimEvents.ExtractionComplete) != 0)
                PlayOrFallback(_extraction, 1f, _ward, 0.9f);
            // The interim phase-2 sting was cue-gameover at 0.35 — a DEFEAT
            // sound on the boss's escalation, which told the player the wrong
            // thing at the loudest moment in the fight.
            if ((events & SimEvents.BossPhase2) != 0)
                PlayOrFallback(_bossPhase2, 1f, _gameover, 0.35f);
            if ((events & SimEvents.ComboFinisher) != 0)
                PlayOrFallback(_comboFinisher, 1f, _kill, 0.7f);
            if ((events & SimEvents.BossSpawned) != 0)
                PlayOrFallback(_bossSpawned, 1f, _wave, 0.9f);
        }

        /// <summary>
        /// Play the dedicated cue when it shipped, else the interim variation.
        /// Keeping BOTH in one call makes the fallback visible at the event
        /// site — a separate null check further up would drift out of sight the
        /// first time someone reorders the list.
        /// </summary>
        void PlayOrFallback(AudioClip preferred, float preferredVolume,
                            AudioClip fallback, float fallbackVolume)
        {
            if (preferred != null) Play(preferred, preferredVolume);
            else Play(fallback, fallbackVolume);
        }
    }
}
